grammar = {
	0 : ('Sx', [b'A_aug', b';', b'Sx'], False),
	1 : ('Sx', [b'A_sim', b';', b'Sx'], False),
	2 : ('Sx', [b'A_aug', b';'], True),
	3 : ('Sx', [b'A_sim', b';'], True),
	4 : ('Sx', [b'A_dro', b';'], False),
	5 : ('Sx', [b'Ctrl', b'Sx'], False),
	6 : ('Sx', [b'Ctrl'], False),
	7 : ('Sx', [b'Fun', b';', b'Sx'], False),
	8 : ('Sx', [b'Fun', b';'], False),
	9 : ('A_aug', [b'ID', b'Ao', b'Ex'], True),
	10 : ('A_sim', [b'ID', b'=', b'Ex'], True),
	11 : ('A_sim', [b'ID', b'=', b'Dc'], True),
	12 : ('Ao', [b'+='], True),
	13 : ('Ao', [b'-='], True),
	14 : ('Ao', [b'*='], True),
	15 : ('Ao', [b'/='], True),
	16 : ('Ao', [b'%='], True),
	17 : ('Ao', [b'>>='], True),
	18 : ('Ao', [b'<<='], True),
	19 : ('Ao', [b'&='], True),
	20 : ('Ao', [b'|='], True),
	21 : ('Ao', [b'^='], True),
	22 : ('Ao', [b'**='], True),
	23 : ('Ex', [b'Or_l'], True),
	24 : ('Or_l', [b'Or_l', b'||', b'And_l'], True),
	25 : ('Or_l', [b'And_l'], True),
	26 : ('And_l', [b'And_l', b'&&', b'Not_l'], True),
	27 : ('And_l', [b'Not_l'], True),
	28 : ('Not_l', [b'!', b'Not_l'], True),
	29 : ('Not_l', [b'Lx'], True),
	30 : ('Lx', [b'Lx', b'Lo', b'Or_b'], True),
	31 : ('Lx', [b'Or_b'], True),
	32 : ('Lo', [b'<'], True),
	33 : ('Lo', [b'>'], True),
	34 : ('Lo', [b'<='], False),
	35 : ('Lo', [b'>='], True),
	36 : ('Lo', [b'=='], True),
	37 : ('Lo', [b'!='], True),
	38 : ('Or_b', [b'Or_b', b'|', b'Xor_b'], True),
	39 : ('Or_b', [b'Xor_b'], True),
	40 : ('Xor_b', [b'Xor_b', b'^', b'And_b'], True),
	41 : ('Xor_b', [b'And_b'], True),
	42 : ('And_b', [b'And_b', b'&', b'Shift'], True),
	43 : ('And_b', [b'Shift'], True),
	44 : ('Shift', [b'Shift', b'>>', b'Ax'], True),
	45 : ('Shift', [b'Shift', b'<<', b'Ax'], True),
	46 : ('Shift', [b'Ax'], True),
	47 : ('Ax', [b'Ax', b'+', b'Af'], True),
	48 : ('Ax', [b'Ax', b'-', b'Af'], True),
	49 : ('Ax', [b'Af'], True),
	50 : ('Af', [b'Af', b'*', b'Ap'], True),
	51 : ('Af', [b'Af', b'%', b'Ap'], True),
	52 : ('Af', [b'Af', b'/', b'Ap'], True),
	53 : ('Af', [b'Ap'], True),
	54 : ('Ap', [b'At', b'**', b'Ap'], True),
	55 : ('Ap', [b'At'], True),
	56 : ('At', [b'Si', b'NUMBER'], True),
	57 : ('At', [b'STRING'], True),
	58 : ('At', [b'Si', b'ID'], True),
	59 : ('At', [b'Si', b'(', b'Ex', b')'], True),
	60 : ('At', [b'poi', b'(', b'Lla', b')'], True),
	61 : ('At', [b'list', b'(', b'Par', b')'], True),
	62 : ('At', [b'input', b'(', b'Eps', b')'], True),
	63 : ('Par', [b'Ex', b'Pas'], True),
	64 : ('Par', [b'\xce\xb5'], True),
	65 : ('Pas', [b',', b'Ex', b'Pas'], True),
	66 : ('Pas', [b'\xce\xb5'], True),
	67 : ('Si', [b'Si', b'+'], True),
	68 : ('Si', [b'Si', b'-'], True),
	69 : ('Si', [b'Si', b'~'], True),
	70 : ('Si', [b'\xce\xb5'], True),
	71 : ('Dc', [b'drone', b'(', b'STRING', b',', b'Ex', b')'], True),
	89 : ('Dc', [b'connect', b'(', b'STRING', b')'], True),
	90 : ('Dc', [b'drone', b'(', b'ID', b',', b'ID', b')'], True),
	72 : ('Lla', [b'Ex', b',', b'Ex', b',', b'Ex'], True),
	73 : ('Fun', [b'move_to', b'(', b'ID', b',', b'Lla', b')'], True),
	74 : ('Fun', [b'rotate', b'(', b'ID', b',', b'Lla', b')'], True),
	75 : ('Fun', [b'print', b'(', b'Eps', b')'], True),
	76 : ('Fun', [b'speed', b'(', b'ID', b',', b'Ex', b')'], True),
	77 : ('Fun', [b'mission', b'(', b'ID', b',', b'Ex', b')'], True),
	78 : ('Ctrl', [b'For'], False),
	79 : ('Ctrl', [b'While'], False),
	80 : ('Ctrl', [b'If'], False),
	81 : ('For', [b'for', b'(', b'ID', b':', b'Ex', b',', b'Ex', b',', b'Ex', b')', b'{', b'Sx', b'}'], False),
	82 : ('While', [b'while', b'(', b'Ex', b')', b'{', b'Sx', b'}'], False),
	83 : ('If', [b'if', b'(', b'Ex', b')', b'{', b'Sx', b'}', b'El'], False),
	84 : ('El', [b'else', b'{', b'Sx', b'}'], False),
	85 : ('El', [b'elif', b'(', b'Ex', b')', b'{', b'Sx', b'}', b'El'], False),
	86 : ('El', [b'\xce\xb5'], False),
	87 : ('Eps', [b'Ex'], True),
	88 : ('Eps', [b'\xce\xb5'], True),
}
